### ISSUE TITLE
Issue in installing due to "py_sg"

### ISSUE THREAD

**Issue by GluTbl** [0-duke/wdpassport-utils#28]
It seems like we should use "py3_sg".
The step was working in my previous Os version. But i face issue when i installed latest "Ubuntu 22.04.1 LTS"

**Comment by GluTbl** [comment]
Solved:
1) Fork the repo
2) run ```sudo apt install python3 python3-dev python3-pip git```  as mentioned in readme file
1) install py3_sg ```sudo python3 -m pip install py3_sg```

Now lets modified the forked repo

2) change ```import py_sg```  to ```import py3_sg as py_sg```  in  ```wdpassport-utils.py``` 
3) delete line ```py_sg @ git+https://github.com/crypto-universe/py_sg```, requirement line from ```setup.py``` . Because we installed py3_sg
4) run ```sudo pip3 install git+https://github.com/Your_Fork_Repo_Location/wdpassport-utils```

**Comment by Sr-Curmudgeon** [comment]
I've been using wdpassport-utils on Ubuntu with no problem for several years. I just updated to Ubuntu 22.04 LTS and  encountered the error due to "py-sg" vs "py3-sg". I'm not a programmer so could you give instructions for a user to modify the installation on their machine until a general fix is available? Thanks!

**Comment by 0-duke** [comment]
Thanks for the public guidance on this. The updated version reflect the above instructions.
